# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
_extends: .github
name-template: javacc-maven-plugin-$NEXT_MINOR_VERSION
tag-template: javacc-maven-plugin-$NEXT_MINOR_VERSION
